@startuml
skin BlueModern

participant Funder
actor Management
' participant Model 
participant IAP

== Funding Phase ==

Management -> Funder: Motivates for funding
activate Funder
Funder -> Management: Provides funding
deactivate Funder

== Management Phase ==

Management  -> IAP: Controls IAP spread
activate IAP
Management  <- IAP: Monitors impact

deactivate IAP


@enduml